// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Personnel_Division.Models;

[Table("Division")]
public partial class Division
{
    [Key]
    public int ID_Division { get; set; }

    public int Number_employees { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; }

    [InverseProperty("ID_DivisionNavigation")]
    public virtual ICollection<Vacancy> Vacancies { get; set; } = new List<Vacancy>();

    [InverseProperty("ID_DivisionNavigation")]
    public virtual ICollection<Worker_Division> Worker_Divisions { get; set; } = new List<Worker_Division>();
}