// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Personnel_Division.Models;

[Table("Sanction")]
public partial class Sanction
{
    [Key]
    public int ID_Sanction { get; set; }

    public int ID_Worker { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column(TypeName = "date")]
    public DateTime Date_writ { get; set; }

    [Required]
    [StringLength(300)]
    [Unicode(false)]
    public string Writ { get; set; }

    [ForeignKey("ID_Worker")]
    [InverseProperty("Sanctions")]
    public virtual Worker ID_WorkerNavigation { get; set; }
}