// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Personnel_Division.Models;

[Table("Vacation")]
public partial class Vacation
{
    [Key]
    public int ID_Vacation { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column(TypeName = "date")]
    public DateTime Start_date { get; set; }

    [Column(TypeName = "date")]
    public DateTime End_date { get; set; }

    [InverseProperty("ID_VacationNavigation")]
    public virtual ICollection<Worker_Vacation> Worker_Vacations { get; set; } = new List<Worker_Vacation>();
}