// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Personnel_Division.Models;

[Table("Worker_Division")]
public partial class Worker_Division
{
    [Key]
    public int ID_Worker_Division { get; set; }

    public int ID_Worker { get; set; }

    public int ID_Division { get; set; }

    [ForeignKey("ID_Division")]
    [InverseProperty("Worker_Divisions")]
    public virtual Division ID_DivisionNavigation { get; set; }

    [ForeignKey("ID_Worker")]
    [InverseProperty("Worker_Divisions")]
    public virtual Worker ID_WorkerNavigation { get; set; }
}