// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Personnel_Division.Models;

[Table("Worker")]
public partial class Worker
{
    [Key]
    public int ID_Worker { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Surname { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Middle_name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Post { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Specialization { get; set; }

    public int? Grade_class { get; set; }

    [Column(TypeName = "date")]
    public DateTime Date_employment { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date_termination { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Working_conditions { get; set; }

    public int Passport_data { get; set; }

    [InverseProperty("ID_WorkerNavigation")]
    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    [InverseProperty("ID_WorkerNavigation")]
    public virtual ICollection<Sanction> Sanctions { get; set; } = new List<Sanction>();

    [InverseProperty("ID_WorkerNavigation")]
    public virtual ICollection<Worker_Division> Worker_Divisions { get; set; } = new List<Worker_Division>();

    [InverseProperty("ID_WorkerNavigation")]
    public virtual ICollection<Worker_Vacancy> Worker_Vacancies { get; set; } = new List<Worker_Vacancy>();

    [InverseProperty("ID_WorkerNavigation")]
    public virtual ICollection<Worker_Vacation> Worker_Vacations { get; set; } = new List<Worker_Vacation>();
}