// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Personnel_Division.Models;

[Table("Worker_Vacancy")]
public partial class Worker_Vacancy
{
    [Key]
    public int ID_Worker_Vacancy { get; set; }

    public int ID_Worker { get; set; }

    public int ID_Vacancy { get; set; }

    [ForeignKey("ID_Vacancy")]
    [InverseProperty("Worker_Vacancies")]
    public virtual Vacancy ID_VacancyNavigation { get; set; }

    [ForeignKey("ID_Worker")]
    [InverseProperty("Worker_Vacancies")]
    public virtual Worker ID_WorkerNavigation { get; set; }
}